services:
  - type: web
    name: freshai-detection
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
